from django.core.management.base import BaseCommand
from core.models import Pet

class Command(BaseCommand):
    help = 'Adds sample pets to the database'

    def handle(self, *args, **kwargs):
        # Sample pets data
        pets_data = [
            {
                'name': 'Luna',
                'species': 'dog',
                'breed': 'Golden Retriever',
                'age': 2,
                'gender': 'female',
                'description': 'Luna is a friendly and energetic Golden Retriever who loves to play fetch and go for long walks.',
                'health_status': 'Excellent health, up to date on all vaccinations',
                'is_vaccinated': True,
                'is_neutered': True,
                'status': 'available',
                'photo': 'pets/luna.jpg',
            },
            {
                'name': 'Max',
                'species': 'dog',
                'breed': 'German Shepherd',
                'age': 3,
                'gender': 'male',
                'description': 'Max is a loyal and intelligent German Shepherd. He is great with kids and makes an excellent guard dog.',
                'health_status': 'Good health, regular check-ups',
                'is_vaccinated': True,
                'is_neutered': True,
                'status': 'available',
                'photo': 'pets/max.jpg',
            },
            {
                'name': 'Bella',
                'species': 'cat',
                'breed': 'Siamese',
                'age': 1,
                'gender': 'female',
                'description': 'Bella is a playful Siamese cat who loves attention and cuddles.',
                'health_status': 'Excellent health, recently checked by vet',
                'is_vaccinated': True,
                'is_neutered': True,
                'status': 'available',
                'photo': 'pets/bella.jpg',
            },
            {
                'name': 'Charlie',
                'species': 'cat',
                'breed': 'Persian',
                'age': 4,
                'gender': 'male',
                'description': 'Charlie is a calm and gentle Persian cat who enjoys lounging in sunny spots.',
                'health_status': 'Good health, regular grooming required',
                'is_vaccinated': True,
                'is_neutered': True,
                'status': 'available',
                'photo': 'pets/charlie.jpg',
            },
            {
                'name': 'Rocky',
                'species': 'dog',
                'breed': 'Bulldog',
                'age': 2,
                'gender': 'male',
                'description': 'Rocky is a friendly bulldog who loves to play and snuggle.',
                'health_status': 'Good health, regular exercise needed',
                'is_vaccinated': True,
                'is_neutered': False,
                'status': 'available',
                'photo': 'pets/rocky.jpg',
            },
            {
                'name': 'Milo',
                'species': 'cat',
                'breed': 'British Shorthair',
                'age': 2,
                'gender': 'male',
                'description': 'Milo is a curious and playful British Shorthair who loves to chase toys.',
                'health_status': 'Healthy, regular vet visits',
                'is_vaccinated': True,
                'is_neutered': True,
                'status': 'available',
                'photo': 'pets/milo.jpg',
            },
            {
                'name': 'Coco',
                'species': 'bird',
                'breed': 'Parrot',
                'age': 1,
                'gender': 'female',
                'description': 'Coco is a talkative parrot who loves to mimic sounds and interact with people.',
                'health_status': 'Excellent health, loves seeds and fruits',
                'is_vaccinated': False,
                'is_neutered': False,
                'status': 'available',
                'photo': 'pets/coco.jpg',
            },
            {
                'name': 'Buddy',
                'species': 'dog',
                'breed': 'Beagle',
                'age': 5,
                'gender': 'male',
                'description': 'Buddy is a loyal Beagle who enjoys outdoor adventures and sniffing around.',
                'health_status': 'Healthy, needs daily walks',
                'is_vaccinated': True,
                'is_neutered': True,
                'status': 'available',
                'photo': 'pets/buddy.jpg',
            },
            {
                'name': 'Daisy',
                'species': 'cat',
                'breed': 'Maine Coon',
                'age': 3,
                'gender': 'female',
                'description': 'Daisy is a gentle Maine Coon who loves to be brushed and petted.',
                'health_status': 'Excellent health, regular grooming',
                'is_vaccinated': True,
                'is_neutered': True,
                'status': 'available',
                'photo': 'pets/daisy.jpg',
            },
            {
                'name': 'Shadow',
                'species': 'other',
                'breed': 'Rabbit',
                'age': 1,
                'gender': 'male',
                'description': 'Shadow is a shy but sweet rabbit who enjoys quiet environments.',
                'health_status': 'Healthy, needs fresh vegetables daily',
                'is_vaccinated': False,
                'is_neutered': False,
                'status': 'available',
                'photo': 'pets/shadow.jpg',
            },
        ]

        # Create pets
        for pet_data in pets_data:
            Pet.objects.create(**pet_data)
            self.stdout.write(self.style.SUCCESS(f'Successfully added pet "{pet_data["name"]}"')) 