# Generated by Django 5.2 on 2025-04-22 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('species', models.CharField(choices=[('dog', 'Köpek'), ('cat', 'Kedi'), ('bird', 'Kuş'), ('other', 'Diğer')], max_length=50, verbose_name='Tür')),
                ('breed', models.CharField(max_length=100, verbose_name='Irk')),
                ('age', models.PositiveIntegerField(verbose_name='Yaş')),
                ('gender', models.CharField(choices=[('male', 'Erkek'), ('female', 'Dişi')], max_length=50, verbose_name='Cinsiyet')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('health_status', models.TextField(verbose_name='Sağlık Durumu')),
                ('is_vaccinated', models.BooleanField(default=False, verbose_name='Aşıları Tam mı?')),
                ('is_neutered', models.BooleanField(default=False, verbose_name='Kısırlaştırıldı mı?')),
                ('photo', models.ImageField(upload_to='pets/', verbose_name='Fotoğraf')),
                ('status', models.CharField(choices=[('available', 'Sahiplendirmeye Uygun'), ('pending', 'Sahiplendirme Sürecinde'), ('adopted', 'Sahiplendirildi')], default='available', max_length=50, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evcil Hayvan',
                'verbose_name_plural': 'Evcil Hayvanlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(verbose_name='Adres')),
                ('has_pets', models.BooleanField(default=False, verbose_name='Başka Evcil Hayvanınız Var mı?')),
                ('current_pets', models.TextField(blank=True, null=True, verbose_name='Mevcut Evcil Hayvanlarınız')),
                ('reason', models.TextField(verbose_name='Sahiplenme Nedeni')),
                ('status', models.CharField(choices=[('pending', 'İnceleniyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=50, verbose_name='Başvuru Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Başvuran')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pet', verbose_name='Evcil Hayvan')),
            ],
            options={
                'verbose_name': 'Sahiplenme Başvurusu',
                'verbose_name_plural': 'Sahiplenme Başvuruları',
                'ordering': ['-created_at'],
            },
        ),
    ]
