# Generated by Django 5.2 on 2025-05-07 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('other', 'Other')], max_length=50, verbose_name='Species')),
                ('breed', models.CharField(max_length=100, verbose_name='Breed')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50, verbose_name='Gender')),
                ('description', models.TextField(verbose_name='Description')),
                ('health_status', models.TextField(verbose_name='Health Status')),
                ('is_vaccinated', models.BooleanField(default=False, verbose_name='Vaccinated')),
                ('is_neutered', models.BooleanField(default=False, verbose_name='Neutered')),
                ('photo', models.ImageField(upload_to='pets/', verbose_name='Photo')),
                ('status', models.CharField(choices=[('available', 'Available for Adoption'), ('pending', 'Adoption Pending'), ('adopted', 'Adopted')], default='available', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('address', models.TextField(verbose_name='Address')),
                ('has_pets', models.BooleanField(default=False, verbose_name='Do you have other pets?')),
                ('current_pets', models.TextField(blank=True, null=True, verbose_name='Current Pets')),
                ('reason', models.TextField(verbose_name='Reason for Adoption')),
                ('status', models.CharField(choices=[('pending', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50, verbose_name='Application Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Adoption Application',
                'verbose_name_plural': 'Adoption Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
